AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: production
      DefinitionBody:
        swagger: '2.0'
        info:
          title: 'My REST API'
          version: '1.0'
        paths:
          /items:
            get:
              responses:
                '200':
                  description: 'OK'
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
          /items/{itemId}:
            get:
              parameters:
                - name: itemId
                  in: path
                  required: true
                  type: string
              responses:
                '200':
                  description: 'OK'
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: sam_app/
    Events:
      Api1:
        Type: Api
        Properties:
          Path: /items
          Method: GET
      Api2:
        Type: Api
        Properties:
          Path: /items/{itemId}
          Method: GET
  
